### ISSUE TITLE
Deploy blazor-v0.1.0

### ISSUE THREAD

**Issue by maraf** [neptuo/Recollection#27]
- [x] Setup DNS.
- [x] Update CORS.
- [x] #25 Prepare container for API.
- [x] Issue SSL certificate API.
- [x] Publish API.
- [x] Setup Blazor site.
- [x] Publish Blazor client.
